SET( CPACK_PACKAGE_NAME ${APP_NAME} )
SET( CPACK_PACKAGE_VENDOR ${VENDOR} )
SET( CPACK_PACKAGE_VERSION_MAJOR ${MAJOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_MINOR ${MINOR_VERSION} )
SET( CPACK_PACKAGE_VERSION_PATCH ${PATCH_VERSION}${SOURCE_MODIFIED_STR} )
SET( CPACK_PACKAGE_DESCRIPTION ${APP_DESC} )
SET( CPACK_PACKAGE_HOMEPAGE_URL ${PRODUCT_HOMEPAGE} )
#SET( CPACK_PACKAGE_ICON ${CMAKE_SOURCE_DIR}/Ui/resources/logo.bmp )
#SET( CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/" )
#SET( CPACK_RESOURCE_FILE_README ${CMAKE_SOURCE_DIR}/README.txt )
SET( CPACK_MONOLITHIC_INSTALL ON )
SET( CPACK_PACKAGE_EXECUTABLES ${APP_NAME}-gui ${APP_NAME})
SET( CPACK_CREATE_DESKTOP_LINKS ${APP_NAME}-gui )
SET( CPACK_THREADS 2 )

set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
    CreateShortCut \\\"$DESKTOP\\\\${APP_NAME}.lnk\\\" \\\"$INSTDIR\\\\${APP_NAME}-gui.exe\\\"
")

set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "
    Delete \\\"$DESKTOP\\\\${APP_NAME}.lnk\\\"
")

IF(UNIX)
    SET(CPACK_GENERATOR STGZ TGZ)
    IF(CMAKE_SIZEOF_VOID_P EQUAL 4) #32 bit
        SET(CPACK_SYSTEM_NAME x86)
    ELSEIF(CMAKE_SIZEOF_VOID_P EQUAL 8) #64 bit
        SET(CPACK_SYSTEM_NAME x86_64)
    ENDIF()
ELSE()
    SET( CPACK_GENERATOR ZIP NSIS )
    SET( CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH} )
ENDIF()

#message( STATUS "CPACK_PACKAGE_NAME=${CPACK_PACKAGE_NAME}" )
#message( STATUS "CPACK_PACKAGE_VENDOR=${CPACK_PACKAGE_VENDOR}" )
#message( STATUS "CPACK_PACKAGE_VERSION_MAJOR=${CPACK_PACKAGE_VERSION_MAJOR}" )
#message( STATUS "CPACK_PACKAGE_VERSION_MINOR=${CPACK_PACKAGE_VERSION_MINOR}" )
#message( STATUS "CPACK_PACKAGE_VERSION_PATCH=${CPACK_PACKAGE_VERSION_PATCH}" )
#message( STATUS "CPACK_PACKAGE_DESCRIPTION=${CPACK_PACKAGE_DESCRIPTION}" )
#message( STATUS "CPACK_PACKAGE_HOMEPAGE_URL=${CPACK_PACKAGE_HOMEPAGE_URL}" )
#message( STATUS "CPACK_PACKAGE_ICON=${CPACK_PACKAGE_ICON}" )
#message( STATUS "CPACK_RESOURCE_FILE_LICENSE=${CPACK_RESOURCE_FILE_LICENSE}" )
#message( STATUS "CPACK_RESOURCE_FILE_README=${CPACK_RESOURCE_FILE_README}" )
#message( STATUS "CPACK_MONOLITHIC_INSTALL=${CPACK_MONOLITHIC_INSTALL}" )
#message( STATUS "CPACK_THREADS=${CPACK_THREADS}" )
#message( STATUS "CPACK_GENERATOR=${CPACK_GENERATOR}" )


SET( CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON )
SET( CPACK_NSIS_EXECUTABLES_DIRECTORY "." )

include( CPack )

