find_package(Git REQUIRED)
find_package(CreateVersion REQUIRED)

GetGitInfo(${CMAKE_SOURCE_DIR} GIT_VERSION_INFO)
STRING(TIMESTAMP BUILD_DATE "%m/%d/%Y" UTC)
STRING(TIMESTAMP BUILD_TIME "%H:%M:%SUTC" UTC)

SET( MAJOR_VERSION    1 )
SET( MINOR_VERSION    00 )
SET( PATCH_VERSION    ${GIT_VERSION_INFO_REV} )

SET( APP_NAME         "EZ Git" )
SET( APP_NAME_COMPRESSED "EZGit" )
SET( APP_DESC         "Application to make Git as EZ as possible" )
SET( APP_LOGO         "application.png" )
SET( APP_EXEC         "EZ Git-gui.exe" )
SET( VENDOR           "Towel 42 Development, LLC" )
SET( HOMEPAGE         "www.towel42.com" )
SET( PRODUCT_HOMEPAGE "github.com/towel42-com/EZGit" )
SET( EMAIL            "support@towel42.com" )

SET( START_YEAR 2025 )

SET(COPYRIGHT "Copyright ( C ) <COPYRIGHT_YEARS> Scott Aron Bloom and ${VENDOR}")

CreateVersion( ${CMAKE_SOURCE_DIR} 
    TEMPLATE ${CMAKE_SOURCE_DIR}/T42-CMakeUtils/Modules/Version.h.in
    START_YEAR ${START_YEAR}
    MAJOR ${MAJOR_VERSION} 
    MINOR ${MINOR_VERSION} 
    PATCH ${GIT_VERSION_INFO_REV}
    DIFF  ${GIT_VERSION_INFO_DIFF}
    APP_NAME ${APP_NAME} 
    VENDOR ${VENDOR} 
    HOMEPAGE ${HOMEPAGE} 
    PRODUCT_HOMEPAGE ${PRODUCT_HOMEPAGE} 
    EMAIL ${EMAIL} 
    BUILD_DATE ${BUILD_DATE}
    BUILD_TIME ${BUILD_TIME}
    COPYRIGHT  ${COPYRIGHT}
)

CreateTagAndPackageTarget( ${MAJOR_VERSION} ${MINOR_VERSION} )

string(REGEX REPLACE "^0*([0-9]+)$" "\\1" APPX_VERSION_MAJOR "${MAJOR_VERSION}")
string(REGEX REPLACE "^0*([0-9]+)$" "\\1" APPX_VERSION_MINOR "${MINOR_VERSION}")
string(REGEX REPLACE "^0*([0-9]+)$" "\\1" APPX_VERSION_PATCH_HIGH "${VERSION_FILE_PATCH_VERSION_HIGH}")
string(REGEX REPLACE "^0*([0-9]+)$" "\\1" APPX_VERSION_PATCH_LOW  "${VERSION_FILE_PATCH_VERSION_LOW}")
set(APPX_MANIFEST_VERSION "${APPX_VERSION_MAJOR}.${APPX_VERSION_MINOR}.${APPX_VERSION_PATCH_HIGH}.${APPX_VERSION_PATCH_LOW}")
