find_package(Git REQUIRED)
find_package(CreateVersion REQUIRED)

GetGitInfo(${CMAKE_SOURCE_DIR} GIT_VERSION_INFO)
STRING(TIMESTAMP BUILD_DATE "%m/%d/%Y" UTC)
STRING(TIMESTAMP BUILD_TIME "%H:%M:%SUTC" UTC)

SET( MAJOR_VERSION    0 )
SET( MINOR_VERSION    0 )
SET( PATCH_VERSION    ${GIT_VERSION_INFO_REV} )
SET( SOURCE_MODIFIED  ${GIT_VERSION_INFO_DIFF} )
if ( ${SOURCE_MODIFIED} )
    SET( SOURCE_MODIFIED_STR  "-MODIFIEDSOURCE" )
else()
    SET( SOURCE_MODIFIED_STR  "" )
endif()

SET( APP_NAME         "EZ Git" )
SET( APP_DESC         "Application to make Git as EZ as possible" )
SET( VENDOR           "Towel 42 Development, LLC" )
SET( HOMEPAGE         "www.towel42.com" )
SET( PRODUCT_HOMEPAGE "www.towel42.com" )
SET( EMAIL            "support@towel42.com" )
SET( START_YEAR 2025 )
STRING(TIMESTAMP CURR_YEAR "%Y")
if ( ${START_YEAR} STREQUAL ${CURR_YEAR} )
    SET( COPYRIGHT_YEARS "${START_YEAR}"  )
else()
    SET( COPYRIGHT_YEARS "${START_YEAR}-${CURR_YEAR}" )
endif()

#message( STATUS "START_YEAR=${START_YEAR}" )
#message( STATUS "CURR_YEAR=${CURR_YEAR}" )
#message( STATUS "COPYRIGHT_YEARS=${COPYRIGHT_YEARS}" )
SET(COPYRIGHT "Copyright ( C ) ${COPYRIGHT_YEARS} ${VENDOR}")
#message( STATUS "COPYRIGHT=${COPYRIGHT}" )

CreateVersion( ${CMAKE_SOURCE_DIR} ${CMAKE_SOURCE_DIR}/CMakeSupport/Version.h.in
    MAJOR ${MAJOR_VERSION} 
    MINOR ${MINOR_VERSION} 
    PATCH ${PATCH_VERSION}
    DIFF  ${SOURCE_MODIFIED}
    APP_NAME ${APP_NAME} 
    VENDOR ${VENDOR} 
    HOMEPAGE ${HOMEPAGE} 
    PRODUCT_HOMEPAGE ${PRODUCT_HOMEPAGE} 
    EMAIL ${EMAIL} 
    BUILD_DATE ${BUILD_DATE}
    BUILD_TIME ${BUILD_TIME}
    COPYRIGHT  ${COPYRIGHT}
)

CreateTagAndPackageTarget( ${MAJOR_VERSION} ${MINOR_VERSION} )
